### ISSUE TITLE
Code cleanup

### ISSUE THREAD

**Issue by MakMuftic** [NodeFactoryIo/filecoin-metamask-snap#39]
**Subtasks:**
- [x] Rename `BlockInfo` type
- [x] Restructure Message types
- [x] Write basic code documentation (adapter and API methods)
- [x] Refactor balance formating
- [x] Finish predefined configurations
- [x] Define default values for `gasprice` and `gaslimit`
- [x] Refactor message status to reflect message CID (not block CID)
